<?php
/**
 * Created by PhpStorm.
 * User: wenqidong
 * Date: 2018/5/17
 * Time: 下午3:20
 */
namespace Home\Controller\Mobile;

use Home\Controller\Common\BaseController;
use Think\Controller;

class IndexController extends BaseController {

    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(!session('play')){
//            $this->redirect('/home/mobile/login/index');
        }
    }

    public function ready(){
        $this->display();
    }

    public function play(){
        $this->display();
    }

    public function result(){
        $this->display();
    }

    public function login(){
        $this->display();
    }

}