<?php
/**
 * Created by PhpStorm.
 * User: wenqidong
 * Date: 2018/5/17
 * Time: 下午3:20
 */

namespace Home\Controller\Screen;

use Home\Controller\Common\BaseController;
use Think\Controller;

class IndexController extends BaseController {

    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
//        if(!session('screen')){
//            $this->redirect('/home/screen/index/login');
//        }
    }

    // 首页
    public function index(){
        $this->display('index');
    }

    // 答题
    public function play(){
        $this->display();
    }

    // 结果
    public function result(){
        $this->display();
    }

    public function login(){
        $this->display();
    }

}